
services:  
  api:
    image: node:20.16.0-alpine3.20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["./entrypoint.sh"]
    depends_on:
      database:
        condition: service_started
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - challenge-network
      
  database:
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - challenge-network

networks:
  challenge-network:
    driver: bridge
    